<?php   global$pf_page_contents;$pf_page_contents=array_merge($pf_page_contents,['pf_show_gallery' =>function(){$postID=isset($_GET['post'])?$_GET['post']:0;get_header();try{$imgs=json_decode(get_post_meta($postID,'gallery_images',!0));}catch(Exception$e){echo "_meta parseJson error.";}$gallery_data=["title"=>"","images"=>[],"back_url"=>get_the_permalink($postID),"back_text"=> '<i class="pandastudio-icons-left"></i>'._t8('返回'),"prev_btn"=>'<i class="pandastudio-icons-left"></i>',"next_btn"=>'<i class="pandastudio-icons-right"></i>' ];if(!is_array($imgs)){$imgs=[];}foreach($imgs as $img){$thumb=pd_get_thumbnail_by_url($img,"medium");$full=$img;$gallery_data['images'][]=['thumbnail' =>$thumb,'full' =>$full];}$gallery_data_json=json_encode($gallery_data);?>
		<div id="gallery">
			<script type="application/json" id="gallery-data">
				<?php  echo $gallery_data_json;?>
			</script>
		</div>
		</div></div></body></html>
		<?php 
},'pf_single_gallery_slider' =>function(){$el=pf_element()["createElement"];$postID=get_the_ID();try{$imgs=json_decode(_meta('gallery_images'));}catch(Exception$e){echo "_meta parseJson error.";}if(!is_array($imgs)){$imgs=[];}$images=[];foreach($imgs as $img){$thumb=pd_get_thumbnail_by_url($img);$images[]=$thumb;}$images=json_encode($images);echo $el("div",['class'=>"gallery_slider",'data-images'=>pf_string_encode($images)],[$el("h1",["class"=>"title"],get_the_title($postID)),$el("div",["class"=>"info"],[$el("span",["class"=>"reads","data-toggle"=>"tooltip","title"=>_t8('已读')],[$el("i",["class"=>"pandastudio-icons-book-reader"]),$el('span',['data-number-type'=>'reads'],get_post_meta($postID,'views',!0)?:(get_post_meta($postID,'bigfa_ding',!0)?:0))]),$el("span",["class"=>"likes","data-toggle"=>"tooltip","title"=>_t8('点赞')],[$el("i",["class"=>"pandastudio-icons-heart"]),$el('span',['data-number-type'=>'likes'],get_post_meta($postID,'bigfa_ding',!0)?:0)]),$el("span",["class"=>"comments","data-toggle"=>"tooltip","title"=>_t8('评论')],[$el("i",["class"=>"pandastudio-icons-comment"]),get_comments_number($postID)]),]),$el("a",["class"=>"play","href"=>add_query_arg(['action'=>'show_gallery','post'=>$postID],admin_url('admin-post.php')),'target'=>"_blank" ],'<i class="pandastudio-icons-play"></i><span>'._t8('放映相册').'</span>')]);},'pf_category_gallery_slider' =>function(){global$wp_query;$cat_str=$wp_query->queried_object->label ?:$wp_query->queried_object->name;$post_ids=wp_list_pluck($wp_query->posts,"ID");$all_thumbs=[];foreach($post_ids as $postID){try{$imgs=json_decode(get_post_meta($postID,'gallery_images',!0));}catch(Exception$e){echo "_meta parseJson error.";}if(!is_array($imgs)){$imgs=[];}foreach($imgs as $img){$thumb=pd_get_thumbnail_by_url($img);$all_thumbs[]=$thumb;}}$selected_index=array_rand($all_thumbs,count($all_thumbs)<0x0a?count($all_thumbs):0x0a);$selected_thumbs=[];foreach($selected_index as $i){$selected_thumbs[]=$all_thumbs[$i];}$images=json_encode($selected_thumbs);$el=pf_element()["createElement"];echo $el("div",['class'=>"gallery_slider",'data-images'=>pf_string_encode($images),'style'=>"height:360px" ],$el("h1",["class"=>"title"],$cat_str));},'pf_category_gallery_list'=> function(){global$wp_query;$post_ids=wp_list_pluck($wp_query->posts,"ID");?>
		<div class="clearfix">
			<div class="row post-card-row">
				<?php  do_action('pf_the_taxonomy_articles',$post_ids,0);?>
			</div>
		</div>
		<?php  }]);add_action("admin_post_show_gallery",$pf_page_contents['pf_show_gallery']);add_action("admin_post_nopriv_show_gallery",$pf_page_contents['pf_show_gallery']);add_action("pf_main_column_single(gallery)",$pf_page_contents['pf_single_gallery_slider']);add_action("pf_main_column_single(gallery)",$pf_page_contents['pf_single_post_content']);add_action("pf_main_column_single(gallery)",$pf_page_contents['pf_single_post_comment']);add_action("pf_main_column_taxonomy(gallery-category)",$pf_page_contents['pf_category_gallery_slider']);add_action("pf_main_column_taxonomy(gallery-category)",$pf_page_contents['pf_category_gallery_list']);add_action("pf_main_column_taxonomy(gallery)",$pf_page_contents['pf_category_gallery_slider']);add_action("pf_main_column_taxonomy(gallery)",$pf_page_contents['pf_category_gallery_list']);add_filter("pf_the_article_card",function($default,$post_id,$type_id,$sn){if(get_post_type($post_id)=='gallery'){$el=pf_element()["createElement"];$_=pf_element()["returnResult"];$href=get_permalink($post_id);return $el('div',['class'=>'gallery-card-col col-xxs-6 col-xs-6 col-sm-4 col-md-4 col-lg-3 col-xl-3'],$el("div",['class'=>'gallery-card'],[$el("div",['class'=>'showbox'],$_(function()use($el,$post_id,$href){$result=[];try{$imgs=json_decode(get_post_meta($post_id,'gallery_images',!0));}catch(Exception$e){echo "_meta parseJson error.";}if(!is_array($imgs)){$imgs=[];}for($j=0;$j<(count($imgs)>=0x00003?0x00003:count($imgs));$j++){$medium=pd_get_thumbnail_by_url($imgs[$j],"medium");$result[]=$el("a",['href'=>$href],$el("img",['src'=>$medium]));}return $result;})),$el("a",["class"=>"title","href"=>$href],$el("span",[],get_the_title($post_id))),]));}return $default;},0x000004,0x0a);add_filter("pf_search_allowed_posttype",function($arg){$arg['gallery']=_t8('相册');return $arg;});add_filter("modify_pandastudio_posttype_and_meta",function($posttype_and_meta_json){$new_file=file_get_contents("posttype_and_meta_gallery.json",0x001);$new_arr=json_decode($new_file,!0);$newPostTypes=array_merge($posttype_and_meta_json['myPostTypes']['posttypes'],$new_arr['myPostTypes']['posttypes']);$posttype_and_meta_json['myPostTypes']['posttypes']=$newPostTypes;$newColumns=array_merge($posttype_and_meta_json['myPostTypes']['columns'],$new_arr['myPostTypes']['columns']);$posttype_and_meta_json['myPostTypes']['columns']=$newColumns;$newMeta=array_merge($posttype_and_meta_json['meta'],$new_arr['meta']);$posttype_and_meta_json['meta']=$newMeta;$newComponents=array_merge($posttype_and_meta_json['components'],$new_arr['components']);$posttype_and_meta_json['components']=$newComponents;return $posttype_and_meta_json;});add_action('pandastudio_framework_options_submenu_data',function(){?>
	<tr>
		<th><label><?php  _et8('旧主题相册数据升级');?></label></th>
		<td>
			<a class="button" href="<?php  echo add_query_arg('action','update_gallery_data',admin_url('admin.php'));?>"><?php  _et8('立刻升级');?></a>
			<p class="description"><?php  _et8('新用户无视此选项');?></p>
			<p class="description"><?php  _et8('reBorn、niRvana老用户首次使用时请升级数据，否则将出现报错行为。此操作不可逆！');?></p>
			<p class="description"><?php  _et8('WordPress要求：meta的数据类型应为string/boolean/integer/number。原相册数据为array，因此根据要求转换为string进行存储');?></p>
		</td>
	</tr>
	<?php });add_action("admin_action_update_gallery_data",function(){if(current_user_can('manage_options')){$count_gallery=(array)wp_count_posts('gallery');$all=0;$status=[];foreach($count_gallery as $statu=>$number){$all+= $number;$status[]=$statu;}query_posts(['post_type'=> ['gallery'],'posts_per_page'=> $all,'post_status'=> $status]);if(have_posts()){while(have_posts()){the_post();$post_id=get_the_id();$metas=['gallery_images',];foreach($metas as $key=>$metaName){$metaVal=_meta($metaName,!1);if(is_array($metaVal)){$metaVal=json_encode($metaVal);update_post_meta($post_id,$metaName,$metaVal);}}}}wp_redirect(add_query_arg('message',_t8('reBorn、niRvana主题中使用的meta字段已处理完毕'),wp_get_referer()));}});