<?php
global $pf_page_contents;$pf_page_contents = array_merge($pf_page_contents,[
'pf_posttype_archive_faq_slider' => function(){global $wp_query;$posts = [[
'title' => _t8('常见问题'),'background' => _URL(THEME_ROOT.'/assets/frontend/theme_modules/static/faq_bg.jpg'),'type' => '','categories' => "<i class='pandastudio-icons-books'></i>"._t8n('已收录 {{1}} 个常见问题{{单数}}','已收录 {{1}} 个常见问题{{复数}}',$wp_query->found_posts)]];$posts = apply_filters('pf_the_faq_slider',$posts);pf_get_slider($posts);},'pf_category_faq_list' => function(){global $wp_query;$post_ids = wp_list_pluck($wp_query->posts, "ID");$term_id = isset($wp_query->queried_object->term_id) ? $wp_query->queried_object->term_id : $wp_query->query_vars["post_type"];?><div class="clearfix"><div class="row post-card-row"><?php do_action('pf_the_taxonomy_articles',$post_ids, $term_id); ?></div></div><?php
},'pf_single_faq_slider' => function(){global $wp_query;$postID = get_the_ID();$posts = [[
'title' => get_the_title($postID),'background' => _URL(THEME_ROOT.'/assets/frontend/theme_modules/static/faq_bg.jpg'),'type' => '','categories' => "<i class='pandastudio-icons-books'></i>"._t8('常见问题')]];$posts = apply_filters('pf_the_faq_slider',$posts);pf_get_slider($posts);},]);add_action("pf_main_column_taxonomy(faq)",$pf_page_contents['pf_posttype_archive_faq_slider']);add_action("pf_main_column_taxonomy(faq)",$pf_page_contents['pf_category_faq_list']);add_filter("pf_the_article_card",function($default, $post_id, $type_id, $sn){if (get_post_type($post_id) == 'faq') {$el = pf_element()["createElement"];$_ = pf_element()["returnResult"];return $el('div',['class'=>'faq-card-col col-xxs-12'],[
$el('div',['class'=>'question','@click'=>'this.toggle_answer(event,el)'],[
$el('i',['class'=>'pandastudio-icons-right']),$el('span',[],get_the_title($post_id))]),$el('div',['class'=>'answer','style'=>'display:none'],[
$el('div',[],get_the_content(null,false,$post_id)),$el('div',['class'=>'open_new'],$el('div',['class'=>'flag'],$el('div',['class'=>'content'],$el('a',['href'=>get_permalink($post_id),'data-toggle'=>'tooltip','title'=>_t8('作为文章打开')],$el('i', ['class'=>'pandastudio-icons-link'])))))])]
);}return $default;},4,10);add_action("pf_main_column_single(faq)",$pf_page_contents['pf_single_faq_slider']);add_action("pf_main_column_single(faq)",$pf_page_contents['pf_single_post_content']);add_filter("pf_search_allowed_posttype",function($arg){$arg['faq'] = _t8('常见问题');return $arg;});add_filter("modify_pandastudio_posttype_and_meta",function($posttype_and_meta_json){$new_file = file_get_contents("posttype_and_meta_faq.json",1);$new_arr = json_decode($new_file,true);$newPostTypes = array_merge($posttype_and_meta_json['myPostTypes']['posttypes'],$new_arr['myPostTypes']['posttypes']);$posttype_and_meta_json['myPostTypes']['posttypes'] = $newPostTypes;$newColumns = array_merge($posttype_and_meta_json['myPostTypes']['columns'],$new_arr['myPostTypes']['columns']);$posttype_and_meta_json['myPostTypes']['columns'] = $newColumns;$newMeta = array_merge($posttype_and_meta_json['meta'],$new_arr['meta']);$posttype_and_meta_json['meta'] = $newMeta;$newComponents = array_merge($posttype_and_meta_json['components'],$new_arr['components']);$posttype_and_meta_json['components'] = $newComponents;return $posttype_and_meta_json;});add_action('pandastudio_framework_options_submenu_data',function(){?><tr><th><label><?php _et8('旧主题常见问题数据升级'); ?></label></th><td><a class="button" href="<?php echo add_query_arg('action','update_faq_data',admin_url('admin.php')); ?>"><?php _et8('立刻升级'); ?></a><p class="description"><?php _et8('新用户无视此选项'); ?></p><p class="description"><?php _et8('niRvana老用户首次使用时请升级数据，否则FAQ不显示数据。此操作不可逆！'); ?></p><p class="description"><?php _et8('原数据存储在文章Meta中，现修改到文章内容区域'); ?></p></td></tr><?php
});add_action("admin_action_update_faq_data",function(){if (current_user_can('manage_options')) {$count_faq = (array)wp_count_posts('faq');$all = 0;$status = [];foreach ($count_faq as $statu => $number) {$all += $number;$status[] = $statu;}query_posts([
'post_type'=> ['faq'],'posts_per_page'=> $all,'post_status'=> $status
]);if ( have_posts() ) {while ( have_posts() ) {the_post();$post_id = get_the_id();$faq_str = _meta('faq_answer');if ($faq_str) {wp_update_post([
'ID'=>$post_id,'post_content' => $faq_str
]);delete_post_meta($post_id, 'faq_answer');}}}wp_redirect( add_query_arg('message',_t8('niRvana主题中FAQ使用的meta字段已处理完毕'),wp_get_referer()) );}});