<?php
$posts = [];if (_opt('frontpage_slider_type','') == 'fixed') {foreach (_opt('frontpage_slider_fixed_posts',[]) as $key => $row) {$postID = $row['post'];$posts[] = [
'title' => get_the_title($postID),'url' => get_the_permalink($postID),'thumbnail' => _thumbnail($postID),'background' => get_post_meta($postID, '日志头图', true),'type' => "<i class='pandastudio-icons-category'></i>".pf_get_category_text($postID),'categories' => "<i class='pandastudio-icons-category'></i>".pf_get_category_text($postID, true),];}} else {$newest_num = intval(_opt('frontpage_slider_newest',0));$like_num = intval(_opt('frontpage_slider_most_likes',0));$comment_num = intval(_opt('frontpage_slider_most_comments',0));$views_num = intval(_opt('frontpage_slider_most_views',0));$ids = [];if ($newest_num > 0) {$args = array('post_type' => 'post','post_status' => 'publish','post__not_in' => $ids,//排除已筛选的文章
'posts_per_page' => $newest_num,);$query_posts = new WP_Query();$query_posts->query($args);$i = $newest_num;while( $query_posts->have_posts() && $i > 0){$query_posts->the_post();$postID = get_the_ID();$ids[] = $postID;$posts[] = [
'title' => get_the_title(),'url' => get_the_permalink(),'thumbnail' => _thumbnail(),'background' => _meta('日志头图'),'type' => _t8('最新文章'),'categories' => "<i class='pandastudio-icons-category'></i>".pf_get_category_text($postID, true),];$i--;}wp_reset_query();}if ($like_num > 0) {$args = array('post_type' => 'post','post_status' => 'publish','post__not_in' => $ids,//排除已筛选的文章
'posts_per_page' => $like_num,'ignore_sticky_posts' => true,'meta_query' => array(array('key' => 'bigfa_ding','type' => 'NUMERIC'
),),'orderby' => array('bigfa_ding' => 'DESC',),);$query_posts = new WP_Query();$query_posts->query($args);while( $query_posts->have_posts() ){$query_posts->the_post();$postID = get_the_ID();$ids[] = $postID;$posts[] = [
'title' => get_the_title(),'url' => get_the_permalink(),'thumbnail' => _thumbnail(),'background' => _meta('日志头图'),'type' => _t8('点赞最多'),'categories' => "<i class='pandastudio-icons-category'></i>".pf_get_category_text($postID, true),];}wp_reset_query();}if ($comment_num > 0) {$args = array('post_type' => 'post','post_status' => 'publish','post__not_in' => $ids,//排除已筛选的文章
'posts_per_page' => $comment_num,'orderby' => 'comment_count','ignore_sticky_posts' => true
);$query_posts = new WP_Query();$query_posts->query($args);while( $query_posts->have_posts() ){$query_posts->the_post();$postID = get_the_ID();$ids[] = $postID;$posts[] = [
'title' => get_the_title(),'url' => get_the_permalink(),'thumbnail' => _thumbnail(),'background' => _meta('日志头图'),'type' => _t8('评论最多'),'categories' => "<i class='pandastudio-icons-category'></i>".pf_get_category_text($postID, true),];}wp_reset_query();}if ($views_num > 0) {$args = array('post_type' => 'post','post_status' => 'publish','post__not_in' => $ids,//排除已筛选的文章
'posts_per_page' => $views_num,'ignore_sticky_posts' => true,'meta_query' => array(array('key' => 'views','type' => 'NUMERIC'
),),'orderby' => array('views' => 'DESC',),);$query_posts = new WP_Query();$query_posts->query($args);while( $query_posts->have_posts() ){$query_posts->the_post();$postID = get_the_ID();$ids[] = $postID;$posts[] = [
'title' => get_the_title(),'url' => get_the_permalink(),'thumbnail' => _thumbnail(),'background' => _meta('日志头图'),'type' => _t8('阅读最多'),'categories' => "<i class='pandastudio-icons-category'></i>".pf_get_category_text($postID, true),];}wp_reset_query();}}$posts = apply_filters('pf_the_frontpage_slider',$posts);pf_get_slider($posts);