<?php
$posttype_and_meta = get_posttype_and_meta_json_by_RestAPI();$myPostTypes = $posttype_and_meta['myPostTypes'];foreach ($myPostTypes['posttypes'] as $postType) {add_action('init',function() use($postType) {register_post_type( $postType['type'],array('labels' => array('name' => $postType['name'],'singular_name' => ''.$postType['name'],'add_new' => _t8('添加{{1}}',$postType['name']),'add_new_item' => _t8('添加{{1}}',$postType['name']),'edit' => _t8('编辑{{动词}}'),'edit_item' => _t8('编辑{{1}}',$postType['name']),'new_item' => _t8('新{{1}}',$postType['name']),'view' => _t8('查看'),'view_item' => _t8('查看{{1}}',$postType['name']),'search_items' => _t8('搜索{{1}}',$postType['name']),'not_found' => _t8('未找到{{1}}',$postType['name']),'not_found_in_trash' => _t8('回收站未找到{{1}}',$postType['name']),'parent' => _t8('{{1}}父分类',$postType['name'])),'public' => true,'menu_position' => 36,'supports' => array_merge($postType['supports'],!empty($postType['show_in_rest']) ? array('custom-fields') : array()),'show_in_rest' => !empty($postType['show_in_rest']),'taxonomies' => array(),	'menu_icon' => $postType['menu_icon'],'has_archive' => true
));});add_filter('manage_'.$postType['type'].'_posts_columns',function($columns) use($postType) {foreach ($postType['unset_columns'] as $columnName) {unset($columns[$columnName]);}$new_columns = array();foreach ($postType['new_columns'] as $singleColumn) {$new_columns[$singleColumn['name']] = $singleColumn['display'];}$columns = array_merge($columns, $new_columns);if (!empty($columns['tags'])) {$tags = $columns['tags'];unset($columns['tags']);$columns = array_merge($columns, $new_columns, array('tags'=>$tags));}if (!empty($columns['date'])) {$date = $columns['date'];unset($columns['date']);$columns = array_merge($columns, $new_columns, array('date'=>$date));}return $columns;});if (!empty($postType['allow_categorys'])) {add_action('init',function() use($postType) {register_taxonomy($postType['type'].'-category',$postType['type'],array('labels' => array('name' => _t8('{{1}}分类目录',$postType['name']),'add_new_item' => _t8('添加新分类目录'),'new_item_name' => _t8('分类名称')),'show_ui' => true,'show_in_rest' => true,'show_tagcloud' => false,'hierarchical' => true,));});}if (!empty($postType['allow_tags'])) {add_action('init',function() use($postType) {register_taxonomy($postType['type'].'-tag',$postType['type'],array('labels' => array('name' => _t8('{{1}}标签',$postType['name']),'add_new_item' => _t8('添加新标签'),'new_item_name' => _t8('标签名称')),'show_ui' => true,'show_in_rest' => true,'show_tagcloud' => true,'hierarchical' => false,));});}if (!empty($postType['custom_taxonomies'])) {foreach ($postType['custom_taxonomies'] as $item) {add_action('init',function() use($postType,$item) {register_taxonomy($item['taxonomy'],$postType['type'],array('labels' => array('name' => $item['label_name'],'add_new_item' => $item['label_add_new_item'],'new_item_name' => $item['label_new_item_name']
),'show_ui' => $item['show_ui'],'show_in_rest' => true,'show_tagcloud' => $item['show_tagcloud'],'hierarchical' => $item['hierarchical'],));});}}};function custom_columns( $column, $post_id ) {global $myPostTypes;$fillColumns = array();foreach ($myPostTypes['columns'] as $singleColumn) {$fillColumns[$singleColumn['name']] = array('display' => $singleColumn['display'],'meta' => $singleColumn['meta'],'eval' => $singleColumn['eval'],);}$meta = get_post_meta( $post_id, $fillColumns[$column]['meta'], true );switch ($fillColumns[$column]['display']) {	case 'meta':
	echo $meta;	break;	case 'picture':
	echo '<div style="width:80px;height:80px;border-radius:4px;background:url('.$meta.') no-repeat center center / cover"></div>';	break;	case 'href':
	echo '<a href="'.$meta.'" target="_blank">'.$meta.'</a>';	break;	case 'taxonomy':
	$post = get_post($post_id);	$post_type = $post->post_type;	if (get_the_term_list( $post->ID, $post_type.'-category')) {$the_tags = apply_filters( 'the_tags', get_the_term_list( $post->ID, $post_type.'-category', '', '、', '' ), '', '、', '', $post->ID );if ( ! is_wp_error( $the_tags ) ) {echo $the_tags;}}	break;	case 'tag':
	$post = get_post($post_id);	$post_type = $post->post_type;	if (get_the_term_list( $post->ID, $post_type.'-tag')) {$the_tags = apply_filters( 'the_tags', get_the_term_list( $post->ID, $post_type.'-tag', '', '、', '' ), '', '、', '', $post->ID );if ( ! is_wp_error( $the_tags ) ) {echo $the_tags;}}	break;	case 'eval':
	eval($fillColumns[$column]['eval']);	break;	default:
}}add_action( 'manage_posts_custom_column' , 'custom_columns', 10, 2 );?>